### ISSUE TITLE
睡眠无法唤醒

### ISSUE THREAD

**Issue by leowang7267** [darkhandz/XPS15-9550-OSX#10]
Hi，我的电脑现在睡眠之后经常无法唤醒，一直保持黑屏状态

**Comment by darkhandz** [comment]
这个似乎我最初的时候遇到过，不过我在写教程的时候已经解决了的（糊里糊涂）……建议DSDT打上补充补丁试试。

**Comment by leowang7267** [comment]
我好像知道原因了，我是在不充电的情况下唤醒黑屏，其实电脑已经唤醒了，只需要调亮屏幕就行了。。。

**Comment by darkhandz** [comment]
额，那这个问题我也有，需要你点击鼠标或者键盘才亮屏……我以为你说的是唤醒后怎么搞都没反应……

**Comment by darkhandz** [comment]
安装IntelBacklight.kext，亮度补丁要打上BroadWell那个
