### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by gargomester** [darkhandz/XPS15-9550-OSX#2]
This looks like a great tutorial, if you have some time, could you translate it to English?

**Comment by shiweifu** [comment]
You can refer to the tutorial:
http://www.tonymacx86.com/threads/guide-dell-xps-15-9550-skylake-gtx960m-ssd-via-clover-uefi.192598/

**Comment by darkhandz** [comment]
@gargomester 
I'm so sorry, my English is bad... 
as @shiweifu  said, you can refer the tonymacx86's tutorial, my tutorial is also base on it.

**Comment by gargomester** [comment]
No worries, using google translate plus the tutorial at tonymacx86 I managed to get it done. 👍

**Comment by darkhandz** [comment]
@gargomester 
Good luck :)
