### ISSUE TITLE
关于Dellxps15使用三星960pro固态不能被识别问题

### ISSUE THREAD

**Issue by TechmanYao** [darkhandz/XPS15-9550-OSX#24]
我的电脑是dell xps15 9550，最近在hack1Mac 10.11，但是我用的是Samsung 960pro，进去安装界面找不到硬盘进行安装，你知道怎么解决吗？我没有Mac，进不到Mac系统，有没有方法使用Samsung960pro，用的是clover引导。用那个hackrnver就会卡在，删除那个驱动能进去安装界面，但没有硬盘，求解决

**Comment by TechmanYao** [comment]
我的问题解决了

**Comment by darkhandz** [comment]
恭喜
