### ISSUE TITLE
禁止休眠无效，有大神能解决吗？

### ISSUE THREAD

**Issue by allenmien** [darkhandz/XPS15-9550-OSX#34]
节能-休眠时间-永久，可是还是会大概10分钟后黑屏休眠。（因为4K 9550休眠会闪屏的问题，现在打算不休眠达到不闪屏的目的）。
有大神能解决禁止休眠无效的问题吗？

**Comment by allenmien** [comment]
@darkhandz

**Comment by darkhandz** [comment]
试试 `sudo pmset -a autopoweroff 0`
还有`sudo pmset -a sleep 0`

**Comment by allenmien** [comment]
4K 休眠，闪屏的问题还没有办法是吧？

**Comment by darkhandz** [comment]
并不清楚，我的是1080的，没怎么留意4k的事。

**Comment by allenmien** [comment]
好的，谢谢，我先试试这两个禁止休眠的命令

**Comment by allenmien** [comment]
这两个命令依然无法禁止休眠

**Comment by allenmien** [comment]
@darkhandz

**Comment by allenmien** [comment]
已解决

**Comment by allenmien** [comment]
用的imac换到macpro2015解决
