### ISSUE TITLE
哪个版本的系统流畅

### ISSUE THREAD

**Issue by lyt0511** [darkhandz/XPS15-9550-OSX#38]
大大，我想问一下10.11, 12, 13这三个版本的黑苹果哪个能流畅一些呀

**Comment by darkhandz** [comment]
对于我搞iOS开发的来说，有时候没得选择，新的版本Xcode会有最低系统版本要求。
个人觉得10.11.6不错，但是10.13有原生支持第三方NVMe SSD。

**Comment by lyt0511** [comment]
谢谢大大～～
