### ISSUE TITLE
黑手大神求帮助

### ISSUE THREAD

**Issue by allenmien** [darkhandz/XPS15-9550-OSX#39]
4k顶配，完全按照教程来的。
其他没什么问题。有时开机会卡进度条不动，重启才能进来，大概10次有50%的几率。
问一下大概是sm原因，能怎么解决呢？
@darkhandz

**Comment by darkhandz** [comment]
加多一个FakePCIID_Intel_HDMI_Audio.kext驱动到 CLOVER/kexts/Other 里面。[下载地址](https://bitbucket.org/RehabMan/os-x-fake-pci-id/downloads/)

**Comment by allenmien** [comment]
问题解决，非常感谢
