### ISSUE TITLE
耳机杂音大的不能听

### ISSUE THREAD

**Issue by kandra777** [darkhandz/XPS15-9550-OSX#7]
声卡驱动是用cloverconfig.plist配置的ACPI - Fixes里勾选了FixHDA，并且Devices - Audio - Inject 框内填了13的方式来修改的

外放很完美 但是插入耳机后杂音很大  不知道大大有没有时间解决一下

我在网上搜索了很多 但是苦于完全是小白 不懂其中的滋味 

如果我要安装其他驱动来代替已经安装的驱动 不知道我应该怎么操作？

**Comment by darkhandz** [comment]
安装CodecCommander.kext，然后ACPI/Patched里加入SSDT-ALC298.aml

**Comment by kandra777** [comment]
好 我去试试 

再问一下 那之前的那个plist里面还用勾选fixhda和inject框还用填写13吗？

**Comment by kandra777** [comment]
额 出问题了
安装了CodecCommander.kext 然后加入了对应的aml
并且把plist的fixhda去掉勾选 然后把inject取消
现在系统报错 “‘系统音频驱动异常，或耳机／扬声器为接入 请检查和处理”
我装的流程和删除的操作是不是不对啊？

**Comment by kandra777** [comment]
黑大大。你估计睡了 已经弄好了
那个fixhda还是要勾选 inject13也不能删除
然后安装驱动 plist加入列表
重启2次就好了
多谢你了啊 帮了我们好多 建议你可以建个群 这样沟通方便一点 也可以让我们这些新手进步快点
晚安

**Comment by darkhandz** [comment]
inject或者DSDT注入layout-id还是要的。
论坛已有交流群了，我只不过是把自己弄好的东西分享一下而已，没时间去一对一指导呢。
