### ISSUE TITLE
第二部安装系统卡Sound assertion AppleHDADriver at line 3685

### ISSUE THREAD

**Issue by ghost** [darkhandz/XPS15-9550-OSX#8]
![default](https://cloud.githubusercontent.com/assets/24433513/20977163/98d81b08-bcdf-11e6-9378-a7e582674b1f.jpg)
新手比较不懂，完全照教程来，不通过，想在远景论坛找答案，现在服务器升级还未开放。
想问一下有没有头绪？

**Comment by darkhandz** [comment]
你可以暂时去掉AppleALC.kext试试。（用U盘引导比较好修改）
另外你应该说明一下自己的配置，还有做到哪一步。
论坛升级我觉得就是扯……添加下面的内容到hosts里就可以访问了。

```
218.93.127.136 pcbeta.com
218.93.127.136 i.pcbeta.com
218.93.127.136 www.pcbeta.com
218.93.127.136 bbs.pcbeta.com
218.93.127.136 uc.pcbeta.com
218.93.127.136 cdn.pcbeta.static.inimc.com
218.93.127.136 static.template.pcbeta.com
218.93.127.136 group.pcbeta.com
```

**Comment by ghost** [comment]
忘记上传了自己的配置图，购买的低配版XPS15 9550，将32G换成了256G的PM961固态
![2](https://cloud.githubusercontent.com/assets/24433513/20997855/3cfa17ae-bd44-11e6-849c-49a8f6e7e2f0.png)
以下是我导出来的文本配置
[配置表格.txt](https://github.com/darkhandz/XPS15-9550-OSX/files/638431/default.txt)
现在就试试你说的那种方法，如果还有问题再来请教。谢谢。
貌似我没有添加AppleALC.kext，我将你所说的Other文件夹放进去之后没有发现。
整个下载文件当中，看到你放在了More Kext压缩包里面，我应该放进去吗？

**Comment by darkhandz** [comment]
似乎和AppleALC无关，你才到安装前的步骤……
你等了多久才确定它卡住了？

**Comment by ghost** [comment]
很久了吧，半个小时都有了，不过我好像删除错了，误将KEXT文件夹删除了，直接加入了OTHER文件夹在CLOVER

**Comment by darkhandz** [comment]
额，这是不对的，Clover会找不到这些驱动的，你再改正试试。

**Comment by ghost** [comment]
好的，我是重新创建了KEXTS文件夹，将OTHER文件夹放进去了。是这样没错的吗。
原本在文中要求的删除KEXTS文件夹里面的所有文件夹是包括所有文件吗

**Comment by darkhandz** [comment]
是的，其实kexts里面的文件无所谓，里面的文件夹才有影响。
尽量保持 EFI\Clover\Kexts里只有 Other 文件夹会比较简单。

**Comment by ghost** [comment]
按照教程所走，现在完整的重现了教程结果，唯一不足的是关机变成重启，可能是我机器问题，不知道有没有解决方法。

**Comment by darkhandz** [comment]
打上教程里提到的 附加补丁 试试……

**Comment by ghost** [comment]
你好，想问下如果需要让imessage和facetime启用的话有没有什么好的办法呢？另外关机变成重启这个问题到现在还没有找到解决方法😄另外还发现了合盖以及睡眠时变成了重启，自动进入了windows界面。对于睡眠问题，我重新用终端确认了一下我是按照教程重新设置了0休眠来防止这个问题的，不过现在好像失效了。

**Comment by darkhandz** [comment]
im和facetime应该要生成自己的序列号和uuid，boardid 什么的，可以上网搜搜教程。
关机变重启这个问题一般也是由于usb补丁没打导致的，不过按我教程做的话应该没这个问题才对，建议可以试试新的10.12.1教程。

**Comment by ghost** [comment]
好的，感谢指点，近期暂时没时间换新系统试试了，能过完年再折腾吧， 毕竟还是喜欢mac系统的软件，与iOS同步的相对比较好，哈哈哈，先祝你新年快乐。
