### ISSUE TITLE
出现一些问题反馈给您

### ISSUE THREAD

**Issue by GeekASMR** [darkhandz/XPS15-9550-OSX#9]
图片在这里， niceok.cc/1.jpg
已经进行完大部分操作，改完语言重启编程这样

**Comment by darkhandz** [comment]
额，好像看不到你传的图片，描述问题时最好说明你的笔记本配置

**Comment by GeekASMR** [comment]
4k版本的机器 硬盘 nvme pm951 512G 内存 16G cpu6700hq 显卡 960
错误图片 niceok.cc/cuo.jpg

**Comment by darkhandz** [comment]
看上去像是无线驱动引起了Kernel Panic……可以试试把config.plist里面的KextsToPatch下的关于AirPortBrcm4360和IOBluetoothFamily的补丁先disable。
你可以用U盘引导进系统修改。

**Comment by GeekASMR** [comment]
刚刚重新搞了一下，已经完善了，只是触摸板不是很好用 10.11.6

**Comment by GeekASMR** [comment]
商店登录  报错   登录时发生意外错误，  YOUR DEVICE OR COMPUTER COULD NOT BE VERIFED

**Comment by darkhandz** [comment]
要AppStore下载，需要做好[假以太网卡内建](https://github.com/darkhandz/XPS15-9550-OSX#j-假以太网卡内建)和[更多kext驱动](https://github.com/darkhandz/XPS15-9550-OSX#六更多kext驱动)里面的4、5两步。
触摸板用ApplePS2SmartTouchPad会稍比VoodooPS好一点，不过想和Windows10下面的体验一样……或者想和MBP原生的一样……暂时没有人肯无偿花时间去做这样的驱动（硬件厂商也不一定开放技术文档）。

**Comment by GeekASMR** [comment]
我的电脑经常卡死，osx下表现是卡死，win下表现是蓝屏，请问下是和硬盘有关吗。

**Comment by GeekASMR** [comment]
我是看了科技美学的xps15测评才买的。深深的把我给骗了

**Comment by darkhandz** [comment]
OSX运行起来之后我没有死机过（使用两个多月了），Win10虽然我很少跑，但是十多次下来也没见过蓝屏或者死机。
你这个我觉得是硬件问题了，请尽快联系卖家处理。

**Comment by darkhandz** [comment]
另外……建议买机子前，看完多方的评价之后还应该自己去卖场真身感受一下才决定……毕竟不便宜

**Comment by GeekASMR** [comment]
感谢您的耐心解答，通过您的教程，学习到好多，再次感谢您
